# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(596, 219)
        Form.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"  stop:0   rgba(180, 230, 255, 255),\n"
"  stop:1   rgba(255, 255, 255, 255));")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(9, 10, 571, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas,Segoe UI,Calibri,sans-serif")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(87)
        self.label.setFont(font)
        self.label.setStyleSheet("/* 🌤 Background */\n"
"QWidget {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(235,250,255,255),\n"
"        stop:1 rgba(195,225,250,255));\n"
"}\n"
"\n"
"/* 🩶 Default labels */\n"
"QLabel {\n"
"    color: #1c1c1c;\n"
"    color: rgb(24, 105, 255);\n"
"    font-family: \"Consolas\", \"Segoe UI\", \"Calibri\", sans-serif;\n"
"    font-size: 25pt;\n"
"    background: transparent;\n"
"    letter-spacing: 0.5px;\n"
"font-weight: 700;\n"
"    background: transparent;\n"
"    padding: 4px;\n"
"   \n"
"    letter-spacing: 0.5px;\n"
"}\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.path_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.path_lineEdit.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.gridLayout.addWidget(self.path_lineEdit, 0, 1, 1, 1)
        self.browse_pushButton = QtWidgets.QPushButton(self.frame)
        self.browse_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(255, 215, 100, 255),\n"
"        stop:0.5 rgba(255, 160, 40, 255),\n"
"        stop:1 rgba(220, 110, 0, 255));\n"
"    border: 2px solid rgba(150, 70, 0, 190);\n"
"    border-bottom: 4px solid rgba(120, 50, 0, 210);\n"
"    font: 100 18pt \"MS Serif\";\n"
"    border-radius: 14px;\n"
"    padding: 8px 18px;\n"
"    color: rgb(60, 25, 0);\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(255, 230, 130, 255),\n"
"        stop:1 rgba(255, 175, 60, 255));\n"
"    border-color: rgba(170, 90, 0, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(210, 120, 20, 255),\n"
"        stop:1 rgba(170, 80, 0, 255));\n"
"    padding-top: 10px;\n"
"    border-bottom: 2px solid rgba(120, 50, 0, 210);\n"
"}")
        self.browse_pushButton.setObjectName("browse_pushButton")
        self.gridLayout.addWidget(self.browse_pushButton, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delete_pushButton = QtWidgets.QPushButton(self.frame)
        self.delete_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(255, 215, 100, 255),\n"
"        stop:0.5 rgba(240, 80, 80, 255),\n"
"        stop:1 rgba(180, 30, 30, 255));\n"
"    border: 2px solid rgba(90, 0, 0, 190);\n"
"    border-bottom: 4px solid rgba(60, 0, 0, 210);\n"
"    font: 100 18pt \"MS Serif\";\n"
"    border-radius: 14px;\n"
"    padding: 8px 18px;\n"
"    color: rgb(255, 230, 225);\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(255, 230, 130, 255),\n"
"        stop:1 rgba(210, 50, 50, 255));\n"
"    border-color: rgba(110, 0, 0, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(180, 60, 60, 255),\n"
"        stop:1 rgba(120, 20, 20, 255));\n"
"    padding-top: 10px;\n"
"    border-bottom: 2px solid rgba(60, 0, 0, 210);\n"
"}")
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.horizontalLayout.addWidget(self.delete_pushButton)
        self.export_pushButton = QtWidgets.QPushButton(self.frame)
        self.export_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.export_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(255, 215, 100, 255),\n"
"        stop:0.5 rgba(190, 240, 80, 255),\n"
"        stop:1 rgba(142, 220, 49, 255));\n"
"    border: 2px solid rgba(0, 90, 0, 190);\n"
"    border-bottom: 4px solid rgba(0, 60, 0, 210);\n"
"    font: 100 18pt \"MS Serif\";\n"
"    border-radius: 14px;\n"
"    padding: 8px 18px;\n"
"    color: rgb(30, 50, 0);\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(255, 230, 130, 255),\n"
"        stop:1 rgba(170, 240, 80, 255));\n"
"    border-color: rgba(0, 110, 0, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(180, 210, 60, 255),\n"
"        stop:1 rgba(120, 195, 30, 255));\n"
"    padding-top: 10px;\n"
"    border-bottom: 2px solid rgba(0, 60, 0, 210);\n"
"}")
        self.export_pushButton.setObjectName("export_pushButton")
        self.horizontalLayout.addWidget(self.export_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PPTX Notes Extractor (by aymen mahmoudi) V 2.0"))
        self.label.setText(_translate("Form", "PPT notes Extractor"))
        self.browse_pushButton.setText(_translate("Form", "Browse"))
        self.delete_pushButton.setText(_translate("Form", "Delete"))
        self.export_pushButton.setText(_translate("Form", "Export"))
